name: Build and Deploy Laravel Application

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        options:
          - production
          - dev

jobs:
  deploy:
    uses: ./.github/workflows/reusable-build-deploy.yml
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}  # Optional
      aws-region: ${{ secrets.AWS_REGION }}
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
      ecr-repository: ${{ secrets.ECR_REPOSITORY }}
      environment: ${{ github.event.inputs.environment }}
