name: Deploy Laravel App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        default: 'production'
        required: true
        options:
          - production
          - dev
  schedule:
    - cron: "00 00 * * *"

jobs:
  deploy:
    uses: ./.github/workflows/docker-deploy.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
    
