name: caller

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        default: 'production'
        required: true
        options:
          - production
          - dev

  schedule:
    - cron: "30 21 * * *" # Trigger at 9:30 PM daily

jobs:
  deploy:
    uses: ./.github/workflows/docker-deploy.yml
    
      
