name: Build and Deploy Laravel Application

on:
  workflow_call:
    # inputs:
      # aws-region:
      #   description: 'AWS Region for deployment'
      #   required: true
      #   type: string
      # ecr-repository:
      #   description: 'ECR Repository name'
      #   required: true
      #   type: string

    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # Log in to AWS ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t laravel-demo .
          
      - name: Tag & Push Docker image to ECR
        working-directory: backend
        env:
          ecr_registry: ${{ steps.login-ecr.outputs.registry }}
          ecr_repo: "laravel-demo"
        run: |
          docker tag laravel-demo $ecr_registry/$ecr_repo:latest
          docker push $ecr_registry/$ecr_repo:latest

      # # Push Docker image to ECR
      # - name: tag and push
      #   run: |
      #     docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repository }}laravel-demo:latest
