name: Build and Deploy Laravel Application
# Trigger workflow when code is pushed to the 'main' branch
on:
  push:
    branches:
      - main

# workflow-dispatch manual trigger on prod and dev
  workflow_dispatch:
    inputs:
      environment: 
        description: ' deployment environment '
        default: 'production'
        required: true
        options:
         - production 
         - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # aws credentials 
      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_region }}
          

      # Log in to AWS ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t 924144197303.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}laravel-demo:latest .

      # Push Docker image to ECR
      - name: Push Docker image
        run: |
          docker push 924144197303.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}laravel-demo:latest
