name: Build and Deploy Laravel Application
on:

# creating reusable workflow

  workflow_call:
    inputs:
      aws-access-key-id:
        required: false
        type: string
      aws-secret-access-key:
        required: false
        type: string
      aws-session-token:
        required: false
        type: string
      aws-region:
        required: false
        type: string
      aws-account-id:
        required: false
        type: string
      ecr-repository:
        required: false
        type: string


# preparing job for laravel app
jobs:
  build-and-deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    if: ${{ inputs.environment == 'production' }}  # Conditional job execution

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          

      # Log in to AWS ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.aws-region }} | docker login --username AWS --password-stdin ${{ secrets.aws-account-id }}.dkr.ecr.${{ secrets.aws-region }}.amazonaws.com
      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.aws-account-id }}.dkr.ecr.${{ secrets.aws-region }}.amazonaws.com/${{ secrets.ecr-repository }}laravel-demo:latest .
      # Push Docker image to ECR
      - name: Push Docker image
        run: |
          docker push ${{ secrets.aws-account-id }}.dkr.ecr.${{ secrets.aws-region }}.amazonaws.com/${{ secrets.ecr-repository }}laravel-demo:latest